### PR TITLE
Proposal Fixing #55 - future dates

### PR DESCRIPTION
**Pull request by benyanke**
far from done, but a first step showing an example of what future date handling could look like.

Looking for thoughts to see if I should continue.

Tag #55

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Hey @benyanke! What else needs to be done to consider this ready for action? I would love to have this functionality available in the plugin 😄

**Comment by egoist** [comment]
Maybe we could integrate https://date-fns.org/v1.29.0/docs/distanceInWordsToNow to save a lot of works 😄

**Comment by rijkvanzanten** [comment]
Great idea @egoist 😄

Do you also plan on replacing the “regular” date ago with date-fns’ distanceInWords?

**Comment by egoist** [comment]
@rijkvanzanten yeah that seems to support future date as well

**Comment by rijkvanzanten** [comment]
There is one slight problem with the `date-fns` implementation of `distanceInWordsToNow`: it doesn't use the actual word `ago` in the output. E.g. `2 days ago` in vue-timeago is rendered as `2 days` when using `distanceInWordsToNow`.

**Comment by egoist** [comment]
@rijkvanzanten there's an option for that in `distanceInWordsToNow`

btw this landed in v4 😄

**Comment by rijkvanzanten** [comment]
Oh nice! Didn't see that in the docs 🙂 

Thanks for your awesome OSS work @egoist! ❤️

**Comment by benyanke** [comment]
Looks like this is resolved, but is there anything else needing to be done to use it, or will it automatically use before/after when specifying `:since`?

**Comment by rijkvanzanten** [comment]
@benyanke Automatically based on `:since` 🙂 (Just tried this in my app + it's in [the example](https://github.com/egoist/vue-timeago/blob/master/example/app.vue#L15))

**Comment by benyanke** [comment]
Awesome - I must be hitting another bug then.

**Pull request closed without merging**
